/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../common/services/videoUpload';
import * as import4 from './subtitles.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'angularfire2/angularfire2';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './components/vrtvideo-player';
import * as import14 from './components/vrtvideo-player.ngfactory';
var renderType_SubtitlesComponent_Host:import0.RenderComponentType = (null as any);
class _View_SubtitlesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UploadService_0_4:import3.UploadService;
  _SubtitlesComponent_0_5:import4.SubtitlesComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_SubtitlesComponent_Host0,renderType_SubtitlesComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('subtitles-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SubtitlesComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UploadService_0_4 = new import3.UploadService();
    this._SubtitlesComponent_0_5 = new import4.SubtitlesComponent(this.parentInjector.get(import9.Http),this._UploadService_0_4,this.parentInjector.get(import10.AngularFire));
    this._appEl_0.initComponent(this._SubtitlesComponent_0_5,[],compView_0);
    compView_0.create(this._SubtitlesComponent_0_5,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UploadService) && (0 === requestNodeIndex))) { return this._UploadService_0_4; }
    if (((token === import4.SubtitlesComponent) && (0 === requestNodeIndex))) { return this._SubtitlesComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._SubtitlesComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SubtitlesComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SubtitlesComponent_Host === (null as any))) { (renderType_SubtitlesComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_SubtitlesComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SubtitlesComponentNgFactory:import12.ComponentFactory<import4.SubtitlesComponent> = new import12.ComponentFactory<import4.SubtitlesComponent>('subtitles-component',viewFactory_SubtitlesComponent_Host0,import4.SubtitlesComponent);
const styles_SubtitlesComponent:any[] = [];
var renderType_SubtitlesComponent:import0.RenderComponentType = (null as any);
class _View_SubtitlesComponent0 extends import1.AppView<import4.SubtitlesComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  /*private*/ _appEl_74:import2.AppElement;
  _VrtVideoPlayer_74_4:import13.VrtVideoPlayer;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_SubtitlesComponent0,renderType_SubtitlesComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','subtitle-tool');
    this.renderer.setElementAttribute(this._el_0,'style','display:flex;flex-wrap:nowrap;flex-direction:column; width:100%;height:100vh');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','sub-menu');
    this.renderer.setElementAttribute(this._el_2,'style','display:flex; flex-direction:row; flex: 0 1 auto;');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','');
    this.renderer.setElementAttribute(this._el_4,'style',':;');
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_6,'type','button');
    this._text_7 = this.renderer.createText(this._el_6,'New',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','btn btn-secondary');
    this.renderer.setElementAttribute(this._el_9,'type','button');
    this._text_10 = this.renderer.createText(this._el_9,'Open',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'input',(null as any));
    this.renderer.setElementAttribute(this._el_12,'name','video');
    this.renderer.setElementAttribute(this._el_12,'type','file');
    this._text_13 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','');
    this.renderer.setElementAttribute(this._el_16,'style','display:flex; flex-direction:row; flex: 0 1 auto; background: #D2D2D2;');
    this._text_17 = this.renderer.createText(this._el_16,'\n		',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','');
    this.renderer.setElementAttribute(this._el_18,'style',':;');
    this._text_19 = this.renderer.createText(this._el_18,'\n			',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','btn btn-secondary');
    this.renderer.setElementAttribute(this._el_20,'type','button');
    this._text_21 = this.renderer.createText(this._el_20,'Add Subtitle(U)',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n		',(null as any));
    this._text_23 = this.renderer.createText(this._el_16,'\n	',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_25 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','sub-controls');
    this.renderer.setElementAttribute(this._el_25,'style','display:flex; flex-direction:row; flex: 1;');
    this._text_26 = this.renderer.createText(this._el_25,'\n\n		',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','');
    this.renderer.setElementAttribute(this._el_27,'style','flex: 0 0 50%; display:flex;');
    this._text_28 = this.renderer.createText(this._el_27,'\n\n			',(null as any));
    this._text_29 = this.renderer.createText(this._el_27,'\n			',(null as any));
    this._el_30 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','');
    this.renderer.setElementAttribute(this._el_30,'style','flex:1 1 20%; display:flex;flex-direction:column;border:1px solid #f2f2f2;');
    this._text_31 = this.renderer.createText(this._el_30,'\n				',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','');
    this.renderer.setElementAttribute(this._el_32,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_33 = this.renderer.createText(this._el_32,'\n					subtitle 1\n				',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n				',(null as any));
    this._el_35 = this.renderer.createElement(this._el_30,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','');
    this.renderer.setElementAttribute(this._el_35,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_36 = this.renderer.createText(this._el_35,'\n					subtitle 2\n				',(null as any));
    this._text_37 = this.renderer.createText(this._el_30,'\n				',(null as any));
    this._el_38 = this.renderer.createElement(this._el_30,'div',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','');
    this.renderer.setElementAttribute(this._el_38,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_39 = this.renderer.createText(this._el_38,'\n					subtitle 3\n				',(null as any));
    this._text_40 = this.renderer.createText(this._el_30,'\n			',(null as any));
    this._text_41 = this.renderer.createText(this._el_27,'\n\n			',(null as any));
    this._text_42 = this.renderer.createText(this._el_27,'\n			',(null as any));
    this._el_43 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','');
    this.renderer.setElementAttribute(this._el_43,'style','flex:1 1 20%; display:flex;flex-direction:column;border:1px solid #f2f2f2;');
    this._text_44 = this.renderer.createText(this._el_43,'\n				',(null as any));
    this._el_45 = this.renderer.createElement(this._el_43,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','');
    this.renderer.setElementAttribute(this._el_45,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_46 = this.renderer.createText(this._el_45,'\n					template 1\n				',(null as any));
    this._text_47 = this.renderer.createText(this._el_43,'\n				',(null as any));
    this._el_48 = this.renderer.createElement(this._el_43,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','');
    this.renderer.setElementAttribute(this._el_48,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_49 = this.renderer.createText(this._el_48,'\n					template 2\n				',(null as any));
    this._text_50 = this.renderer.createText(this._el_43,'\n			',(null as any));
    this._text_51 = this.renderer.createText(this._el_27,'\n\n			',(null as any));
    this._text_52 = this.renderer.createText(this._el_27,'\n			',(null as any));
    this._el_53 = this.renderer.createElement(this._el_27,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','');
    this.renderer.setElementAttribute(this._el_53,'style','flex:1 1 20%; display:flex;flex-direction:column;border:1px solid #f2f2f2;');
    this._text_54 = this.renderer.createText(this._el_53,'\n				',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','');
    this.renderer.setElementAttribute(this._el_55,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_56 = this.renderer.createText(this._el_55,'\n					inputs here\n				',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n				',(null as any));
    this._el_58 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','');
    this.renderer.setElementAttribute(this._el_58,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_59 = this.renderer.createText(this._el_58,'\n					inputs here\n				',(null as any));
    this._text_60 = this.renderer.createText(this._el_53,'\n				',(null as any));
    this._el_61 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','');
    this.renderer.setElementAttribute(this._el_61,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_62 = this.renderer.createText(this._el_61,'\n					inputs here\n				',(null as any));
    this._text_63 = this.renderer.createText(this._el_53,'\n				',(null as any));
    this._el_64 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','');
    this.renderer.setElementAttribute(this._el_64,'style','flex:0;border:1px solid #f2f2f2;');
    this._text_65 = this.renderer.createText(this._el_64,'\n					inputs here\n				',(null as any));
    this._text_66 = this.renderer.createText(this._el_53,'\n			',(null as any));
    this._text_67 = this.renderer.createText(this._el_27,'\n		',(null as any));
    this._text_68 = this.renderer.createText(this._el_25,'\n		',(null as any));
    this._text_69 = this.renderer.createText(this._el_25,'\n		',(null as any));
    this._el_70 = this.renderer.createElement(this._el_25,'div',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','');
    this.renderer.setElementAttribute(this._el_70,'style','flex: 0 0 50%;');
    this._text_71 = this.renderer.createText(this._el_70,'\n			',(null as any));
    this._el_72 = this.renderer.createElement(this._el_70,'div',(null as any));
    this.renderer.setElementAttribute(this._el_72,'class','');
    this.renderer.setElementAttribute(this._el_72,'style','flex:1 1 0%; display:flex;flex-wrap:nowrap;flex-direction:column;border:1px solid #f2f2f2;');
    this._text_73 = this.renderer.createText(this._el_72,'\n				',(null as any));
    this._el_74 = this.renderer.createElement(this._el_72,'vrtvideo-player',(null as any));
    this.renderer.setElementAttribute(this._el_74,'end','vm.selectedSub.end');
    this.renderer.setElementAttribute(this._el_74,'loop','vm.loop');
    this.renderer.setElementAttribute(this._el_74,'source','vm.meta.movieUrl');
    this.renderer.setElementAttribute(this._el_74,'start','vm.selectedSub.start');
    this.renderer.setElementAttribute(this._el_74,'subs','vm.subs');
    this._appEl_74 = new import2.AppElement(74,72,this,this._el_74);
    var compView_74:any = import14.viewFactory_VrtVideoPlayer0(this.viewUtils,this.injector(74),this._appEl_74);
    this._VrtVideoPlayer_74_4 = new import13.VrtVideoPlayer();
    this._appEl_74.initComponent(this._VrtVideoPlayer_74_4,[],compView_74);
    compView_74.create(this._VrtVideoPlayer_74_4,[],(null as any));
    this._text_75 = this.renderer.createText(this._el_72,'\n			',(null as any));
    this._text_76 = this.renderer.createText(this._el_70,'\n		',(null as any));
    this._text_77 = this.renderer.createText(this._el_25,'\n\n	',(null as any));
    this._text_78 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_79 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_79,'class','');
    this.renderer.setElementAttribute(this._el_79,'style','display:flex; flex-direction:row;');
    this._text_80 = this.renderer.createText(this._el_79,'\n	',(null as any));
    this._text_81 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'change',this.eventHandler(this._handle_change_12_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.VrtVideoPlayer) && (74 === requestNodeIndex))) { return this._VrtVideoPlayer_74_4; }
    return notFoundResult;
  }
  private _handle_change_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.upload($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SubtitlesComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.SubtitlesComponent> {
  if ((renderType_SubtitlesComponent === (null as any))) { (renderType_SubtitlesComponent = viewUtils.createRenderComponentType('/Users/matthiasdevriendt/git/Social-Video-Tools/app/views/public/subtitles/subtitles.component.html',0,import11.ViewEncapsulation.None,styles_SubtitlesComponent,{})); }
  return new _View_SubtitlesComponent0(viewUtils,parentInjector,declarationEl);
}