/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import8 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import9 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import10 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import11 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import12 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import13 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import14 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import15 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import22 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import23 from '@ng-bootstrap/ng-bootstrap/index';
import * as import24 from 'videogular2/core';
import * as import25 from 'videogular2/controls';
import * as import26 from 'videogular2/overlay-play';
import * as import27 from 'videogular2/buffering';
import * as import28 from '@angular/http/src/http_module';
import * as import29 from 'angularfire2/angularfire2';
import * as import30 from '@angular/router/src/router_module';
import * as import31 from '@angular/common/src/localization';
import * as import32 from '@angular/core/src/application_init';
import * as import33 from '@angular/core/src/testability/testability';
import * as import34 from '@angular/core/src/application_ref';
import * as import35 from '@angular/core/src/linker/compiler';
import * as import36 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import37 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import38 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import39 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import40 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import41 from '@angular/core/src/linker/view_utils';
import * as import42 from '@angular/platform-browser/src/browser/title';
import * as import43 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import44 from 'videogular2/src/services/vg-api';
import * as import45 from 'videogular2/src/services/vg-fullscreen-api';
import * as import46 from 'videogular2/src/services/vg-utils';
import * as import47 from 'videogular2/src/events/vg-events';
import * as import48 from 'videogular2/src/states/vg-states';
import * as import49 from '@angular/http/src/backends/browser_xhr';
import * as import50 from '@angular/http/src/base_response_options';
import * as import51 from '@angular/http/src/backends/xhr_backend';
import * as import52 from '@angular/http/src/base_request_options';
import * as import53 from 'angularfire2/auth/auth';
import * as import54 from 'angularfire2/database/database';
import * as import55 from '@angular/common/src/location/location';
import * as import56 from '@angular/router/src/url_tree';
import * as import57 from '@angular/router/src/router_outlet_map';
import * as import58 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import59 from '@angular/router/src/router_preloader';
import * as import60 from './common/extends/extBrowserXhr';
import * as import61 from '@angular/core/src/di/injector';
import * as import62 from '../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import63 from '../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import64 from '../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import65 from '../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import66 from '../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import67 from '../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import68 from '../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import69 from './views/public/subtitles/subtitles.component.ngfactory';
import * as import70 from './views/public/subtitles/components/vrtapps.component.ngfactory';
import * as import71 from './app.component.ngfactory';
import * as import72 from '@angular/core/src/application_tokens';
import * as import73 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import74 from '@angular/platform-browser/src/dom/events/key_events';
import * as import75 from '@angular/core/src/zone/ng_zone';
import * as import76 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import77 from '@angular/common/src/location/platform_location';
import * as import78 from '@angular/common/src/location/location_strategy';
import * as import79 from './views/public/subtitles/subtitles.component';
import * as import80 from './views/public/subtitles/components/vrtapps.component';
import * as import81 from '@angular/router/src/router';
import * as import82 from '@angular/core/src/console';
import * as import83 from '@angular/core/src/i18n/tokens';
import * as import84 from '@angular/core/src/error_handler';
import * as import85 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import86 from '@angular/platform-browser/src/dom/animation_driver';
import * as import87 from '@angular/core/src/render/api';
import * as import88 from '@angular/core/src/security';
import * as import89 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import90 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import91 from '@angular/http/src/interfaces';
import * as import92 from '@angular/http/src/http';
import * as import93 from 'angularfire2/tokens';
import * as import94 from 'angularfire2/auth/auth_backend';
import * as import95 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import96 from '@angular/router/src/router_config_loader';
import * as import97 from '@angular/router/src/router_state';
import * as import98 from '@angular/core/src/i18n/tokens';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _NgbAccordionModule_5:import7.NgbAccordionModule;
  _NgbAlertModule_6:import8.NgbAlertModule;
  _NgbButtonsModule_7:import9.NgbButtonsModule;
  _NgbCarouselModule_8:import10.NgbCarouselModule;
  _NgbCollapseModule_9:import11.NgbCollapseModule;
  _NgbDatepickerModule_10:import12.NgbDatepickerModule;
  _NgbDropdownModule_11:import13.NgbDropdownModule;
  _NgbModalModule_12:import14.NgbModalModule;
  _NgbPaginationModule_13:import15.NgbPaginationModule;
  _NgbPopoverModule_14:import16.NgbPopoverModule;
  _NgbProgressbarModule_15:import17.NgbProgressbarModule;
  _NgbRatingModule_16:import18.NgbRatingModule;
  _NgbTabsetModule_17:import19.NgbTabsetModule;
  _NgbTimepickerModule_18:import20.NgbTimepickerModule;
  _NgbTooltipModule_19:import21.NgbTooltipModule;
  _NgbTypeaheadModule_20:import22.NgbTypeaheadModule;
  _NgbModule_21:import23.NgbModule;
  _VgCore_22:import24.VgCore;
  _VgControlsModule_23:import25.VgControlsModule;
  _VgOverlayPlayModule_24:import26.VgOverlayPlayModule;
  _VgBufferingModule_25:import27.VgBufferingModule;
  _HttpModule_26:import28.HttpModule;
  _AngularFireModule_27:import29.AngularFireModule;
  _ROUTER_FORROOT_GUARD_28:any;
  _RouterModule_29:import30.RouterModule;
  _AppModule_30:import1.AppModule;
  __LOCALE_ID_31:any;
  __NgLocalization_32:import31.NgLocaleLocalization;
  _ErrorHandler_33:any;
  _ApplicationInitStatus_34:import32.ApplicationInitStatus;
  _Testability_35:import33.Testability;
  _ApplicationRef__36:import34.ApplicationRef_;
  __ApplicationRef_37:any;
  __Compiler_38:import35.Compiler;
  __APP_ID_39:any;
  __DOCUMENT_40:any;
  __HAMMER_GESTURE_CONFIG_41:import36.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_42:any[];
  __EventManager_43:import37.EventManager;
  __DomSharedStylesHost_44:import38.DomSharedStylesHost;
  __AnimationDriver_45:any;
  __DomRootRenderer_46:import39.DomRootRenderer_;
  __RootRenderer_47:any;
  __DomSanitizer_48:import40.DomSanitizerImpl;
  __Sanitizer_49:any;
  __ViewUtils_50:import41.ViewUtils;
  __IterableDiffers_51:any;
  __KeyValueDiffers_52:any;
  __SharedStylesHost_53:any;
  __Title_54:import42.Title;
  __RadioControlRegistry_55:import43.RadioControlRegistry;
  __VgAPI_56:import44.VgAPI;
  __VgFullscreenAPI_57:import45.VgFullscreenAPI;
  __VgUtils_58:import46.VgUtils;
  __VgEvents_59:import47.VgEvents;
  __VgStates_60:import48.VgStates;
  __BrowserXhr_61:import49.BrowserXhr;
  __ResponseOptions_62:import50.BaseResponseOptions;
  __XSRFStrategy_63:any;
  __XHRBackend_64:import51.XHRBackend;
  __RequestOptions_65:import52.BaseRequestOptions;
  __Http_66:any;
  __FirebaseUserConfig_67:any;
  __FirebaseConfig_68:any;
  __FirebaseApp_69:any;
  __AuthBackend_70:any;
  __WindowLocation_71:any;
  __FirebaseAuthConfig_72:any;
  __AngularFireAuth_73:import53.AngularFireAuth;
  __FirebaseAuth_74:any;
  __AngularFireDatabase_75:import54.AngularFireDatabase;
  __AngularFire_76:import29.AngularFire;
  __ROUTER_CONFIGURATION_77:any;
  __LocationStrategy_78:any;
  __Location_79:import55.Location;
  __UrlSerializer_80:import56.DefaultUrlSerializer;
  __RouterOutletMap_81:import57.RouterOutletMap;
  __NgModuleFactoryLoader_82:import58.SystemJsNgModuleLoader;
  __ROUTES_83:any[];
  __Router_84:any;
  __ActivatedRoute_85:any;
  _NoPreloading_86:import59.NoPreloading;
  _PreloadingStrategy_87:any;
  _RouterPreloader_88:import59.RouterPreloader;
  __PreloadAllModules_89:import59.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_90:any[];
  __ExtBrowserXhr_91:import60.ExtBrowserXhr;
  __TRANSLATIONS_FORMAT_92:any;
  constructor(parent:import61.Injector) {
    super(parent,[
      import62.NgbAlertNgFactory,
      import63.NgbDatepickerNgFactory,
      import64.NgbModalBackdropNgFactory,
      import65.NgbModalWindowNgFactory,
      import66.NgbPopoverWindowNgFactory,
      import67.NgbTooltipWindowNgFactory,
      import68.NgbTypeaheadWindowNgFactory,
      import69.SubtitlesComponentNgFactory,
      import70.VrtAppsComponentNgFactory,
      import71.AppComponentNgFactory
    ]
    ,[import71.AppComponentNgFactory]);
  }
  get _LOCALE_ID_31():any {
    if ((this.__LOCALE_ID_31 == (null as any))) { (this.__LOCALE_ID_31 = (null as any)); }
    return this.__LOCALE_ID_31;
  }
  get _NgLocalization_32():import31.NgLocaleLocalization {
    if ((this.__NgLocalization_32 == (null as any))) { (this.__NgLocalization_32 = new import31.NgLocaleLocalization(this._LOCALE_ID_31)); }
    return this.__NgLocalization_32;
  }
  get _ApplicationRef_37():any {
    if ((this.__ApplicationRef_37 == (null as any))) { (this.__ApplicationRef_37 = this._ApplicationRef__36); }
    return this.__ApplicationRef_37;
  }
  get _Compiler_38():import35.Compiler {
    if ((this.__Compiler_38 == (null as any))) { (this.__Compiler_38 = new import35.Compiler()); }
    return this.__Compiler_38;
  }
  get _APP_ID_39():any {
    if ((this.__APP_ID_39 == (null as any))) { (this.__APP_ID_39 = import72._appIdRandomProviderFactory()); }
    return this.__APP_ID_39;
  }
  get _DOCUMENT_40():any {
    if ((this.__DOCUMENT_40 == (null as any))) { (this.__DOCUMENT_40 = import4._document()); }
    return this.__DOCUMENT_40;
  }
  get _HAMMER_GESTURE_CONFIG_41():import36.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_41 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_41 = new import36.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_41;
  }
  get _EVENT_MANAGER_PLUGINS_42():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_42 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_42 = [
      new import73.DomEventsPlugin(),
      new import74.KeyEventsPlugin(),
      new import36.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_41)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_42;
  }
  get _EventManager_43():import37.EventManager {
    if ((this.__EventManager_43 == (null as any))) { (this.__EventManager_43 = new import37.EventManager(this._EVENT_MANAGER_PLUGINS_42,this.parent.get(import75.NgZone))); }
    return this.__EventManager_43;
  }
  get _DomSharedStylesHost_44():import38.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_44 == (null as any))) { (this.__DomSharedStylesHost_44 = new import38.DomSharedStylesHost(this._DOCUMENT_40)); }
    return this.__DomSharedStylesHost_44;
  }
  get _AnimationDriver_45():any {
    if ((this.__AnimationDriver_45 == (null as any))) { (this.__AnimationDriver_45 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_45;
  }
  get _DomRootRenderer_46():import39.DomRootRenderer_ {
    if ((this.__DomRootRenderer_46 == (null as any))) { (this.__DomRootRenderer_46 = new import39.DomRootRenderer_(this._DOCUMENT_40,this._EventManager_43,this._DomSharedStylesHost_44,this._AnimationDriver_45)); }
    return this.__DomRootRenderer_46;
  }
  get _RootRenderer_47():any {
    if ((this.__RootRenderer_47 == (null as any))) { (this.__RootRenderer_47 = import76._createConditionalRootRenderer(this._DomRootRenderer_46,this.parent.get(import76.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_47;
  }
  get _DomSanitizer_48():import40.DomSanitizerImpl {
    if ((this.__DomSanitizer_48 == (null as any))) { (this.__DomSanitizer_48 = new import40.DomSanitizerImpl()); }
    return this.__DomSanitizer_48;
  }
  get _Sanitizer_49():any {
    if ((this.__Sanitizer_49 == (null as any))) { (this.__Sanitizer_49 = this._DomSanitizer_48); }
    return this.__Sanitizer_49;
  }
  get _ViewUtils_50():import41.ViewUtils {
    if ((this.__ViewUtils_50 == (null as any))) { (this.__ViewUtils_50 = new import41.ViewUtils(this._RootRenderer_47,this._APP_ID_39,this._Sanitizer_49)); }
    return this.__ViewUtils_50;
  }
  get _IterableDiffers_51():any {
    if ((this.__IterableDiffers_51 == (null as any))) { (this.__IterableDiffers_51 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_51;
  }
  get _KeyValueDiffers_52():any {
    if ((this.__KeyValueDiffers_52 == (null as any))) { (this.__KeyValueDiffers_52 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_52;
  }
  get _SharedStylesHost_53():any {
    if ((this.__SharedStylesHost_53 == (null as any))) { (this.__SharedStylesHost_53 = this._DomSharedStylesHost_44); }
    return this.__SharedStylesHost_53;
  }
  get _Title_54():import42.Title {
    if ((this.__Title_54 == (null as any))) { (this.__Title_54 = new import42.Title()); }
    return this.__Title_54;
  }
  get _RadioControlRegistry_55():import43.RadioControlRegistry {
    if ((this.__RadioControlRegistry_55 == (null as any))) { (this.__RadioControlRegistry_55 = new import43.RadioControlRegistry()); }
    return this.__RadioControlRegistry_55;
  }
  get _VgAPI_56():import44.VgAPI {
    if ((this.__VgAPI_56 == (null as any))) { (this.__VgAPI_56 = new import44.VgAPI()); }
    return this.__VgAPI_56;
  }
  get _VgFullscreenAPI_57():import45.VgFullscreenAPI {
    if ((this.__VgFullscreenAPI_57 == (null as any))) { (this.__VgFullscreenAPI_57 = new import45.VgFullscreenAPI()); }
    return this.__VgFullscreenAPI_57;
  }
  get _VgUtils_58():import46.VgUtils {
    if ((this.__VgUtils_58 == (null as any))) { (this.__VgUtils_58 = new import46.VgUtils()); }
    return this.__VgUtils_58;
  }
  get _VgEvents_59():import47.VgEvents {
    if ((this.__VgEvents_59 == (null as any))) { (this.__VgEvents_59 = new import47.VgEvents()); }
    return this.__VgEvents_59;
  }
  get _VgStates_60():import48.VgStates {
    if ((this.__VgStates_60 == (null as any))) { (this.__VgStates_60 = new import48.VgStates()); }
    return this.__VgStates_60;
  }
  get _BrowserXhr_61():import49.BrowserXhr {
    if ((this.__BrowserXhr_61 == (null as any))) { (this.__BrowserXhr_61 = new import49.BrowserXhr()); }
    return this.__BrowserXhr_61;
  }
  get _ResponseOptions_62():import50.BaseResponseOptions {
    if ((this.__ResponseOptions_62 == (null as any))) { (this.__ResponseOptions_62 = new import50.BaseResponseOptions()); }
    return this.__ResponseOptions_62;
  }
  get _XSRFStrategy_63():any {
    if ((this.__XSRFStrategy_63 == (null as any))) { (this.__XSRFStrategy_63 = import28._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_63;
  }
  get _XHRBackend_64():import51.XHRBackend {
    if ((this.__XHRBackend_64 == (null as any))) { (this.__XHRBackend_64 = new import51.XHRBackend(this._BrowserXhr_61,this._ResponseOptions_62,this._XSRFStrategy_63)); }
    return this.__XHRBackend_64;
  }
  get _RequestOptions_65():import52.BaseRequestOptions {
    if ((this.__RequestOptions_65 == (null as any))) { (this.__RequestOptions_65 = new import52.BaseRequestOptions()); }
    return this.__RequestOptions_65;
  }
  get _Http_66():any {
    if ((this.__Http_66 == (null as any))) { (this.__Http_66 = import28.httpFactory(this._XHRBackend_64,this._RequestOptions_65)); }
    return this.__Http_66;
  }
  get _FirebaseUserConfig_67():any {
    if ((this.__FirebaseUserConfig_67 == (null as any))) { (this.__FirebaseUserConfig_67 = {
      apiKey: 'AIzaSyD3BnxjYmXHrP7zUPn8PxXQ1H-SbEzZwsY',
      authDomain: 'localhost',
      databaseURL: 'https://socialvideotool.firebaseio.com',
      storageBucket: 'socialvideotool.appspot.com'
    }
    ); }
    return this.__FirebaseUserConfig_67;
  }
  get _FirebaseConfig_68():any {
    if ((this.__FirebaseConfig_68 == (null as any))) { (this.__FirebaseConfig_68 = import29._getDefaultFirebase(this._FirebaseUserConfig_67)); }
    return this.__FirebaseConfig_68;
  }
  get _FirebaseApp_69():any {
    if ((this.__FirebaseApp_69 == (null as any))) { (this.__FirebaseApp_69 = import29._getFirebase(this._FirebaseConfig_68)); }
    return this.__FirebaseApp_69;
  }
  get _AuthBackend_70():any {
    if ((this.__AuthBackend_70 == (null as any))) { (this.__AuthBackend_70 = import29._getAuthBackend(this._FirebaseApp_69)); }
    return this.__AuthBackend_70;
  }
  get _WindowLocation_71():any {
    if ((this.__WindowLocation_71 == (null as any))) { (this.__WindowLocation_71 = import29._getWindowLocation()); }
    return this.__WindowLocation_71;
  }
  get _FirebaseAuthConfig_72():any {
    if ((this.__FirebaseAuthConfig_72 == (null as any))) { (this.__FirebaseAuthConfig_72 = (null as any)); }
    return this.__FirebaseAuthConfig_72;
  }
  get _AngularFireAuth_73():import53.AngularFireAuth {
    if ((this.__AngularFireAuth_73 == (null as any))) { (this.__AngularFireAuth_73 = new import53.AngularFireAuth(this._AuthBackend_70,this._WindowLocation_71,this._FirebaseAuthConfig_72)); }
    return this.__AngularFireAuth_73;
  }
  get _FirebaseAuth_74():any {
    if ((this.__FirebaseAuth_74 == (null as any))) { (this.__FirebaseAuth_74 = this._AngularFireAuth_73); }
    return this.__FirebaseAuth_74;
  }
  get _AngularFireDatabase_75():import54.AngularFireDatabase {
    if ((this.__AngularFireDatabase_75 == (null as any))) { (this.__AngularFireDatabase_75 = new import54.AngularFireDatabase(this._FirebaseConfig_68,this._FirebaseApp_69)); }
    return this.__AngularFireDatabase_75;
  }
  get _AngularFire_76():import29.AngularFire {
    if ((this.__AngularFire_76 == (null as any))) { (this.__AngularFire_76 = new import29.AngularFire(this._FirebaseConfig_68,this._AngularFireAuth_73,this._AngularFireDatabase_75)); }
    return this.__AngularFire_76;
  }
  get _ROUTER_CONFIGURATION_77():any {
    if ((this.__ROUTER_CONFIGURATION_77 == (null as any))) { (this.__ROUTER_CONFIGURATION_77 = {}); }
    return this.__ROUTER_CONFIGURATION_77;
  }
  get _LocationStrategy_78():any {
    if ((this.__LocationStrategy_78 == (null as any))) { (this.__LocationStrategy_78 = import30.provideLocationStrategy(this.parent.get(import77.PlatformLocation),this.parent.get(import78.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_77)); }
    return this.__LocationStrategy_78;
  }
  get _Location_79():import55.Location {
    if ((this.__Location_79 == (null as any))) { (this.__Location_79 = new import55.Location(this._LocationStrategy_78)); }
    return this.__Location_79;
  }
  get _UrlSerializer_80():import56.DefaultUrlSerializer {
    if ((this.__UrlSerializer_80 == (null as any))) { (this.__UrlSerializer_80 = new import56.DefaultUrlSerializer()); }
    return this.__UrlSerializer_80;
  }
  get _RouterOutletMap_81():import57.RouterOutletMap {
    if ((this.__RouterOutletMap_81 == (null as any))) { (this.__RouterOutletMap_81 = new import57.RouterOutletMap()); }
    return this.__RouterOutletMap_81;
  }
  get _NgModuleFactoryLoader_82():import58.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_82 == (null as any))) { (this.__NgModuleFactoryLoader_82 = new import58.SystemJsNgModuleLoader(this._Compiler_38,this.parent.get(import58.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_82;
  }
  get _ROUTES_83():any[] {
      if ((this.__ROUTES_83 == (null as any))) { (this.__ROUTES_83 = [[
        {
          path: 'subtitles',
          component: import79.SubtitlesComponent
        }
        ,
        {
          path: '',
          component: import80.VrtAppsComponent
        }

      ]
    ]); }
    return this.__ROUTES_83;
  }
  get _Router_84():any {
    if ((this.__Router_84 == (null as any))) { (this.__Router_84 = import30.setupRouter(this._ApplicationRef_37,this._UrlSerializer_80,this._RouterOutletMap_81,this._Location_79,this,this._NgModuleFactoryLoader_82,this._Compiler_38,this._ROUTES_83,this._ROUTER_CONFIGURATION_77)); }
    return this.__Router_84;
  }
  get _ActivatedRoute_85():any {
    if ((this.__ActivatedRoute_85 == (null as any))) { (this.__ActivatedRoute_85 = import30.rootRoute(this._Router_84)); }
    return this.__ActivatedRoute_85;
  }
  get _PreloadAllModules_89():import59.PreloadAllModules {
    if ((this.__PreloadAllModules_89 == (null as any))) { (this.__PreloadAllModules_89 = new import59.PreloadAllModules()); }
    return this.__PreloadAllModules_89;
  }
  get _APP_BOOTSTRAP_LISTENER_90():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_90 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_90 = [import30.initialRouterNavigation(this._Router_84,this._ApplicationRef_37,this._RouterPreloader_88,this._ROUTER_CONFIGURATION_77)]); }
    return this.__APP_BOOTSTRAP_LISTENER_90;
  }
  get _ExtBrowserXhr_91():import60.ExtBrowserXhr {
    if ((this.__ExtBrowserXhr_91 == (null as any))) { (this.__ExtBrowserXhr_91 = new import60.ExtBrowserXhr()); }
    return this.__ExtBrowserXhr_91;
  }
  get _TRANSLATIONS_FORMAT_92():any {
    if ((this.__TRANSLATIONS_FORMAT_92 == (null as any))) { (this.__TRANSLATIONS_FORMAT_92 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_92;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._NgbAccordionModule_5 = new import7.NgbAccordionModule();
    this._NgbAlertModule_6 = new import8.NgbAlertModule();
    this._NgbButtonsModule_7 = new import9.NgbButtonsModule();
    this._NgbCarouselModule_8 = new import10.NgbCarouselModule();
    this._NgbCollapseModule_9 = new import11.NgbCollapseModule();
    this._NgbDatepickerModule_10 = new import12.NgbDatepickerModule();
    this._NgbDropdownModule_11 = new import13.NgbDropdownModule();
    this._NgbModalModule_12 = new import14.NgbModalModule();
    this._NgbPaginationModule_13 = new import15.NgbPaginationModule();
    this._NgbPopoverModule_14 = new import16.NgbPopoverModule();
    this._NgbProgressbarModule_15 = new import17.NgbProgressbarModule();
    this._NgbRatingModule_16 = new import18.NgbRatingModule();
    this._NgbTabsetModule_17 = new import19.NgbTabsetModule();
    this._NgbTimepickerModule_18 = new import20.NgbTimepickerModule();
    this._NgbTooltipModule_19 = new import21.NgbTooltipModule();
    this._NgbTypeaheadModule_20 = new import22.NgbTypeaheadModule();
    this._NgbModule_21 = new import23.NgbModule();
    this._VgCore_22 = new import24.VgCore();
    this._VgControlsModule_23 = new import25.VgControlsModule();
    this._VgOverlayPlayModule_24 = new import26.VgOverlayPlayModule();
    this._VgBufferingModule_25 = new import27.VgBufferingModule();
    this._HttpModule_26 = new import28.HttpModule();
    this._AngularFireModule_27 = new import29.AngularFireModule();
    this._ROUTER_FORROOT_GUARD_28 = import30.provideForRootGuard(this.parent.get(import81.Router,(null as any)));
    this._RouterModule_29 = new import30.RouterModule(this._ROUTER_FORROOT_GUARD_28);
    this._AppModule_30 = new import1.AppModule();
    this._ErrorHandler_33 = import4.errorHandler();
    this._ApplicationInitStatus_34 = new import32.ApplicationInitStatus(this.parent.get(import32.APP_INITIALIZER,(null as any)));
    this._Testability_35 = new import33.Testability(this.parent.get(import75.NgZone));
    this._ApplicationRef__36 = new import34.ApplicationRef_(this.parent.get(import75.NgZone),this.parent.get(import82.Console),this,this._ErrorHandler_33,this,this._ApplicationInitStatus_34,this.parent.get(import33.TestabilityRegistry,(null as any)),this._Testability_35);
    this._NoPreloading_86 = new import59.NoPreloading();
    this._PreloadingStrategy_87 = this._NoPreloading_86;
    this._RouterPreloader_88 = new import59.RouterPreloader(this._Router_84,this._NgModuleFactoryLoader_82,this._Compiler_38,this,this._PreloadingStrategy_87);
    return this._AppModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.NgbAccordionModule)) { return this._NgbAccordionModule_5; }
    if ((token === import8.NgbAlertModule)) { return this._NgbAlertModule_6; }
    if ((token === import9.NgbButtonsModule)) { return this._NgbButtonsModule_7; }
    if ((token === import10.NgbCarouselModule)) { return this._NgbCarouselModule_8; }
    if ((token === import11.NgbCollapseModule)) { return this._NgbCollapseModule_9; }
    if ((token === import12.NgbDatepickerModule)) { return this._NgbDatepickerModule_10; }
    if ((token === import13.NgbDropdownModule)) { return this._NgbDropdownModule_11; }
    if ((token === import14.NgbModalModule)) { return this._NgbModalModule_12; }
    if ((token === import15.NgbPaginationModule)) { return this._NgbPaginationModule_13; }
    if ((token === import16.NgbPopoverModule)) { return this._NgbPopoverModule_14; }
    if ((token === import17.NgbProgressbarModule)) { return this._NgbProgressbarModule_15; }
    if ((token === import18.NgbRatingModule)) { return this._NgbRatingModule_16; }
    if ((token === import19.NgbTabsetModule)) { return this._NgbTabsetModule_17; }
    if ((token === import20.NgbTimepickerModule)) { return this._NgbTimepickerModule_18; }
    if ((token === import21.NgbTooltipModule)) { return this._NgbTooltipModule_19; }
    if ((token === import22.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_20; }
    if ((token === import23.NgbModule)) { return this._NgbModule_21; }
    if ((token === import24.VgCore)) { return this._VgCore_22; }
    if ((token === import25.VgControlsModule)) { return this._VgControlsModule_23; }
    if ((token === import26.VgOverlayPlayModule)) { return this._VgOverlayPlayModule_24; }
    if ((token === import27.VgBufferingModule)) { return this._VgBufferingModule_25; }
    if ((token === import28.HttpModule)) { return this._HttpModule_26; }
    if ((token === import29.AngularFireModule)) { return this._AngularFireModule_27; }
    if ((token === import30.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_28; }
    if ((token === import30.RouterModule)) { return this._RouterModule_29; }
    if ((token === import1.AppModule)) { return this._AppModule_30; }
    if ((token === import83.LOCALE_ID)) { return this._LOCALE_ID_31; }
    if ((token === import31.NgLocalization)) { return this._NgLocalization_32; }
    if ((token === import84.ErrorHandler)) { return this._ErrorHandler_33; }
    if ((token === import32.ApplicationInitStatus)) { return this._ApplicationInitStatus_34; }
    if ((token === import33.Testability)) { return this._Testability_35; }
    if ((token === import34.ApplicationRef_)) { return this._ApplicationRef__36; }
    if ((token === import34.ApplicationRef)) { return this._ApplicationRef_37; }
    if ((token === import35.Compiler)) { return this._Compiler_38; }
    if ((token === import72.APP_ID)) { return this._APP_ID_39; }
    if ((token === import85.DOCUMENT)) { return this._DOCUMENT_40; }
    if ((token === import36.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_41; }
    if ((token === import37.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_42; }
    if ((token === import37.EventManager)) { return this._EventManager_43; }
    if ((token === import38.DomSharedStylesHost)) { return this._DomSharedStylesHost_44; }
    if ((token === import86.AnimationDriver)) { return this._AnimationDriver_45; }
    if ((token === import39.DomRootRenderer)) { return this._DomRootRenderer_46; }
    if ((token === import87.RootRenderer)) { return this._RootRenderer_47; }
    if ((token === import40.DomSanitizer)) { return this._DomSanitizer_48; }
    if ((token === import88.Sanitizer)) { return this._Sanitizer_49; }
    if ((token === import41.ViewUtils)) { return this._ViewUtils_50; }
    if ((token === import89.IterableDiffers)) { return this._IterableDiffers_51; }
    if ((token === import90.KeyValueDiffers)) { return this._KeyValueDiffers_52; }
    if ((token === import38.SharedStylesHost)) { return this._SharedStylesHost_53; }
    if ((token === import42.Title)) { return this._Title_54; }
    if ((token === import43.RadioControlRegistry)) { return this._RadioControlRegistry_55; }
    if ((token === import44.VgAPI)) { return this._VgAPI_56; }
    if ((token === import45.VgFullscreenAPI)) { return this._VgFullscreenAPI_57; }
    if ((token === import46.VgUtils)) { return this._VgUtils_58; }
    if ((token === import47.VgEvents)) { return this._VgEvents_59; }
    if ((token === import48.VgStates)) { return this._VgStates_60; }
    if ((token === import49.BrowserXhr)) { return this._BrowserXhr_61; }
    if ((token === import50.ResponseOptions)) { return this._ResponseOptions_62; }
    if ((token === import91.XSRFStrategy)) { return this._XSRFStrategy_63; }
    if ((token === import51.XHRBackend)) { return this._XHRBackend_64; }
    if ((token === import52.RequestOptions)) { return this._RequestOptions_65; }
    if ((token === import92.Http)) { return this._Http_66; }
    if ((token === import93.FirebaseUserConfig)) { return this._FirebaseUserConfig_67; }
    if ((token === import93.FirebaseConfig)) { return this._FirebaseConfig_68; }
    if ((token === import93.FirebaseApp)) { return this._FirebaseApp_69; }
    if ((token === import94.AuthBackend)) { return this._AuthBackend_70; }
    if ((token === import93.WindowLocation)) { return this._WindowLocation_71; }
    if ((token === import93.FirebaseAuthConfig)) { return this._FirebaseAuthConfig_72; }
    if ((token === import53.AngularFireAuth)) { return this._AngularFireAuth_73; }
    if ((token === import53.FirebaseAuth)) { return this._FirebaseAuth_74; }
    if ((token === import54.AngularFireDatabase)) { return this._AngularFireDatabase_75; }
    if ((token === import29.AngularFire)) { return this._AngularFire_76; }
    if ((token === import30.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_77; }
    if ((token === import78.LocationStrategy)) { return this._LocationStrategy_78; }
    if ((token === import55.Location)) { return this._Location_79; }
    if ((token === import56.UrlSerializer)) { return this._UrlSerializer_80; }
    if ((token === import57.RouterOutletMap)) { return this._RouterOutletMap_81; }
    if ((token === import95.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_82; }
    if ((token === import96.ROUTES)) { return this._ROUTES_83; }
    if ((token === import81.Router)) { return this._Router_84; }
    if ((token === import97.ActivatedRoute)) { return this._ActivatedRoute_85; }
    if ((token === import59.NoPreloading)) { return this._NoPreloading_86; }
    if ((token === import59.PreloadingStrategy)) { return this._PreloadingStrategy_87; }
    if ((token === import59.RouterPreloader)) { return this._RouterPreloader_88; }
    if ((token === import59.PreloadAllModules)) { return this._PreloadAllModules_89; }
    if ((token === import72.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_90; }
    if ((token === import60.ExtBrowserXhr)) { return this._ExtBrowserXhr_91; }
    if ((token === import98.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_92; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__36.ngOnDestroy();
    this._RouterPreloader_88.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);