/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './simple-player';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from 'videogular2/src/vg-player/vg-player';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from 'videogular2/src/vg-media/vg-media';
import * as import13 from '../../../../../node_modules/videogular2/src/vg-player/vg-player.ngfactory';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from 'videogular2/src/services/vg-api';
import * as import16 from '@angular/core/src/security';
var renderType_SimplePlayer_Host:import0.RenderComponentType = (null as any);
class _View_SimplePlayer_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SimplePlayer_0_4:import3.SimplePlayer;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SimplePlayer_Host0,renderType_SimplePlayer_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('simple-player',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SimplePlayer0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SimplePlayer_0_4 = new import3.SimplePlayer();
    this._appEl_0.initComponent(this._SimplePlayer_0_4,[],compView_0);
    compView_0.create(this._SimplePlayer_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SimplePlayer) && (0 === requestNodeIndex))) { return this._SimplePlayer_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SimplePlayer_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SimplePlayer_Host === (null as any))) { (renderType_SimplePlayer_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_SimplePlayer_Host0(viewUtils,parentInjector,declarationEl);
}
export const SimplePlayerNgFactory:import9.ComponentFactory<import3.SimplePlayer> = new import9.ComponentFactory<import3.SimplePlayer>('simple-player',viewFactory_SimplePlayer_Host0,import3.SimplePlayer);
const styles_SimplePlayer:any[] = [];
var renderType_SimplePlayer:import0.RenderComponentType = (null as any);
class _View_SimplePlayer0 extends import1.AppView<import3.SimplePlayer> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _VgPlayer_0_4:import10.VgPlayer;
  _query_VgMedia_0_0:import11.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _VgMedia_2_3:import12.VgMedia;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SimplePlayer0,renderType_SimplePlayer,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'vg-player',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import13.viewFactory_VgPlayer0(this.viewUtils,this.injector(0),this._appEl_0);
    this._VgPlayer_0_4 = new import10.VgPlayer(new import14.ElementRef(this._el_0),this.parentInjector.get(import15.VgAPI));
    this._query_VgMedia_0_0 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._VgPlayer_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'video',(null as any));
    this.renderer.setElementAttribute(this._el_2,'controls','');
    this.renderer.setElementAttribute(this._el_2,'id','singleVideo');
    this.renderer.setElementAttribute(this._el_2,'preload','auto');
    this.renderer.setElementAttribute(this._el_2,'vg-media','');
    this._VgMedia_2_3 = new import12.VgMedia(new import14.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'source',(null as any));
    this.renderer.setElementAttribute(this._el_4,'src','http://static.videogular.com/assets/videos/videogular.mp4');
    this.renderer.setElementAttribute(this._el_4,'type','video/mp4');
    this._text_5 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'source',(null as any));
    this.renderer.setElementAttribute(this._el_6,'src','http://static.videogular.com/assets/videos/videogular.ogg');
    this.renderer.setElementAttribute(this._el_6,'type','video/ogg');
    this._text_7 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_2,'source',(null as any));
    this.renderer.setElementAttribute(this._el_8,'src','http://static.videogular.com/assets/videos/videogular.webm');
    this.renderer.setElementAttribute(this._el_8,'type','video/webm');
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n',(null as any));
      compView_0.create(this._VgPlayer_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_10
      ]
    )],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.VgMedia) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._VgMedia_2_3; }
    if (((token === import10.VgPlayer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._VgPlayer_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._VgMedia_2_3.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_VgMedia_0_0.dirty) {
        this._query_VgMedia_0_0.reset([this._VgMedia_2_3]);
        this._VgPlayer_0_4.medias = this._query_VgMedia_0_0;
        this._query_VgMedia_0_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._VgPlayer_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = this._VgPlayer_0_4.isFullscreen;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'fullscreen',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._VgPlayer_0_4.zIndex;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_0,'z-index',((this.viewUtils.sanitizer.sanitize(import16.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import16.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_SimplePlayer0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SimplePlayer> {
  if ((renderType_SimplePlayer === (null as any))) { (renderType_SimplePlayer = viewUtils.createRenderComponentType('/Users/matthiasdevriendt/git/Social-Video-Tools/app/views/public/subtitles/components/simple-player.html',0,import8.ViewEncapsulation.None,styles_SimplePlayer,{})); }
  return new _View_SimplePlayer0(viewUtils,parentInjector,declarationEl);
}