/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './vrtvideo-player';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from 'videogular2/src/vg-player/vg-player';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from 'videogular2/src/vg-media/vg-media';
import * as import14 from '../../../../../node_modules/videogular2/src/vg-player/vg-player.ngfactory';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from 'videogular2/src/services/vg-api';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/core/src/security';
import * as import19 from 'videogular2/src/vg-controls/vg-controls';
import * as import20 from 'videogular2/src/vg-controls/vg-play-pause/vg-play-pause';
import * as import21 from 'videogular2/src/vg-controls/vg-playback-button/vg-playback-button';
import * as import22 from 'videogular2/src/vg-controls/vg-time-display/vg-time-display';
import * as import23 from 'videogular2/src/vg-controls/vg-scrub-bar/vg-scrub-bar';
import * as import24 from 'videogular2/src/vg-controls/vg-scrub-bar/vg-scrub-bar-current-time/vg-scrub-bar-current-time';
import * as import25 from 'videogular2/src/vg-controls/vg-scrub-bar/vg-scrub-bar-buffering-time/vg-scrub-bar-buffering-time';
import * as import26 from 'videogular2/src/vg-controls/vg-mute/vg-mute';
import * as import27 from 'videogular2/src/vg-controls/vg-fullscreen/vg-fullscreen';
import * as import28 from '../../../../../node_modules/videogular2/src/vg-controls/vg-controls.ngfactory';
import * as import29 from '../../../../../node_modules/videogular2/src/vg-controls/vg-play-pause/vg-play-pause.ngfactory';
import * as import30 from '../../../../../node_modules/videogular2/src/vg-controls/vg-playback-button/vg-playback-button.ngfactory';
import * as import31 from '../../../../../node_modules/videogular2/src/vg-controls/vg-time-display/vg-time-display.ngfactory';
import * as import32 from '../../../../../node_modules/videogular2/src/vg-controls/vg-scrub-bar/vg-scrub-bar.ngfactory';
import * as import33 from '../../../../../node_modules/videogular2/src/vg-controls/vg-scrub-bar/vg-scrub-bar-current-time/vg-scrub-bar-current-time.ngfactory';
import * as import34 from '../../../../../node_modules/videogular2/src/vg-controls/vg-scrub-bar/vg-scrub-bar-buffering-time/vg-scrub-bar-buffering-time.ngfactory';
import * as import35 from '../../../../../node_modules/videogular2/src/vg-controls/vg-mute/vg-mute.ngfactory';
import * as import36 from '../../../../../node_modules/videogular2/src/vg-controls/vg-fullscreen/vg-fullscreen.ngfactory';
var renderType_VrtVideoPlayer_Host:import0.RenderComponentType = (null as any);
class _View_VrtVideoPlayer_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _VrtVideoPlayer_0_4:import3.VrtVideoPlayer;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_VrtVideoPlayer_Host0,renderType_VrtVideoPlayer_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('vrtvideo-player',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_VrtVideoPlayer0(this.viewUtils,this.injector(0),this._appEl_0);
    this._VrtVideoPlayer_0_4 = new import3.VrtVideoPlayer();
    this._appEl_0.initComponent(this._VrtVideoPlayer_0_4,[],compView_0);
    compView_0.create(this._VrtVideoPlayer_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.VrtVideoPlayer) && (0 === requestNodeIndex))) { return this._VrtVideoPlayer_0_4; }
    return notFoundResult;
  }
}
function viewFactory_VrtVideoPlayer_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_VrtVideoPlayer_Host === (null as any))) { (renderType_VrtVideoPlayer_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_VrtVideoPlayer_Host0(viewUtils,parentInjector,declarationEl);
}
export const VrtVideoPlayerNgFactory:import9.ComponentFactory<import3.VrtVideoPlayer> = new import9.ComponentFactory<import3.VrtVideoPlayer>('vrtvideo-player',viewFactory_VrtVideoPlayer_Host0,import3.VrtVideoPlayer);
const styles_VrtVideoPlayer:any[] = [];
var renderType_VrtVideoPlayer:import0.RenderComponentType = (null as any);
class _View_VrtVideoPlayer0 extends import1.AppView<import3.VrtVideoPlayer> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _VgPlayer_4_4:import10.VgPlayer;
  _query_VgMedia_4_0:import11.QueryList<any>;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import12.NgIf;
  _text_7:any;
  _el_8:any;
  _VgMedia_8_3:import13.VgMedia;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import12.NgIf;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_VrtVideoPlayer0,renderType_VrtVideoPlayer,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','videoplayer-container');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','videoplayer-container__player');
    this._text_3 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'vg-player',(null as any));
    this.renderer.setElementAttribute(this._el_4,'style','height: calc(100% - 100px);');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_VgPlayer0(this.viewUtils,this.injector(4),this._appEl_4);
    this._VgPlayer_4_4 = new import10.VgPlayer(new import15.ElementRef(this._el_4),this.parentInjector.get(import16.VgAPI));
    this._query_VgMedia_4_0 = new import11.QueryList<any>();
    this._appEl_4.initComponent(this._VgPlayer_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n\n            ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import17.TemplateRef_(this._appEl_6,viewFactory_VrtVideoPlayer1);
    this._NgIf_6_6 = new import12.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText((null as any),'\n\n            ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'video',(null as any));
    this.renderer.setElementAttribute(this._el_8,'id','singleVideo');
    this.renderer.setElementAttribute(this._el_8,'preload','auto');
    this.renderer.setElementAttribute(this._el_8,'vg-media','');
    this._VgMedia_8_3 = new import13.VgMedia(new import15.ElementRef(this._el_8));
    this._text_9 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_8,(null as any));
    this._appEl_10 = new import2.AppElement(10,8,this,this._anchor_10);
    this._TemplateRef_10_5 = new import17.TemplateRef_(this._appEl_10,viewFactory_VrtVideoPlayer2);
    this._NgIf_10_6 = new import12.NgIf(this._appEl_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n        ',(null as any));
      compView_4.create(this._VgPlayer_4_4,[[].concat([
        this._text_5,
        this._appEl_6,
        this._text_7,
        this._el_8,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText(this._el_2,'\n        \n    ',(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'onPlayerReady',this.eventHandler(this._handle_onPlayerReady_4_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._VgPlayer_4_4.onPlayerReady.subscribe(this.eventHandler(this._handle_onPlayerReady_4_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import12.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    if (((token === import17.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import12.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6; }
    if (((token === import13.VgMedia) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._VgMedia_8_3; }
    if (((token === import10.VgPlayer) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._VgPlayer_4_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:boolean = !this.context.controls;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_6_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._VgMedia_8_3.ngOnInit(); }
    const currVal_5:any = this.context.video;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_10_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_VgMedia_4_0.dirty) {
        this._query_VgMedia_4_0.reset([this._VgMedia_8_3]);
        this._VgPlayer_4_4.medias = this._query_VgMedia_4_0;
        this._query_VgMedia_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._VgPlayer_4_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._VgPlayer_4_4.isFullscreen;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_4,'fullscreen',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._VgPlayer_4_4.zIndex;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementStyle(this._el_4,'z-index',((this.viewUtils.sanitizer.sanitize(import18.SecurityContext.STYLE,currVal_2) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import18.SecurityContext.STYLE,currVal_2).toString()));
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this.context.controls;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_8,'controls',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_onPlayerReady_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onPlayerReady($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_VrtVideoPlayer0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.VrtVideoPlayer> {
  if ((renderType_VrtVideoPlayer === (null as any))) { (renderType_VrtVideoPlayer = viewUtils.createRenderComponentType('/Users/matthiasdevriendt/git/Social-Video-Tools/app/views/public/subtitles/components/vrtvideo-player.html',0,import8.ViewEncapsulation.None,styles_VrtVideoPlayer,{})); }
  return new _View_VrtVideoPlayer0(viewUtils,parentInjector,declarationEl);
}
class _View_VrtVideoPlayer1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _VgControls_0_4:import19.VgControls;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _VgPlayPause_2_4:import20.VgPlayPause;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _VgPlaybackButton_4_4:import21.VgPlaybackButton;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _VgTimeDisplay_6_4:import22.VgTimeDisplay;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _VgScrubBar_8_4:import23.VgScrubBar;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _VgScrubBarCurrentTime_10_4:import24.VgScrubBarCurrentTime;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _VgScrubBarBufferingTime_12_4:import25.VgScrubBarBufferingTime;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _VgTimeDisplay_15_4:import22.VgTimeDisplay;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _VgTimeDisplay_17_4:import22.VgTimeDisplay;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _VgMute_19_4:import26.VgMute;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import2.AppElement;
  _VgFullscreen_21_4:import27.VgFullscreen;
  _text_22:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_VrtVideoPlayer1,renderType_VrtVideoPlayer,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'vg-controls',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import28.viewFactory_VgControls0(this.viewUtils,this.injector(0),this._appEl_0);
    this._VgControls_0_4 = new import19.VgControls(this.parent.parentInjector.get(import16.VgAPI),new import15.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._VgControls_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'vg-play-pause',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import29.viewFactory_VgPlayPause0(this.viewUtils,this.injector(2),this._appEl_2);
    this._VgPlayPause_2_4 = new import20.VgPlayPause(new import15.ElementRef(this._el_2),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_2.initComponent(this._VgPlayPause_2_4,[],compView_2);
    compView_2.create(this._VgPlayPause_2_4,[],(null as any));
    this._text_3 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'vg-playback-button',(null as any));
    this._appEl_4 = new import2.AppElement(4,0,this,this._el_4);
    var compView_4:any = import30.viewFactory_VgPlaybackButton0(this.viewUtils,this.injector(4),this._appEl_4);
    this._VgPlaybackButton_4_4 = new import21.VgPlaybackButton(new import15.ElementRef(this._el_4),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_4.initComponent(this._VgPlaybackButton_4_4,[],compView_4);
    compView_4.create(this._VgPlaybackButton_4_4,[],(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n\n                ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'vg-time-display',(null as any));
    this.renderer.setElementAttribute(this._el_6,'format','mm:ss');
    this.renderer.setElementAttribute(this._el_6,'property','current');
    this._appEl_6 = new import2.AppElement(6,0,this,this._el_6);
    var compView_6:any = import31.viewFactory_VgTimeDisplay0(this.viewUtils,this.injector(6),this._appEl_6);
    this._VgTimeDisplay_6_4 = new import22.VgTimeDisplay(new import15.ElementRef(this._el_6),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_6.initComponent(this._VgTimeDisplay_6_4,[],compView_6);
    compView_6.create(this._VgTimeDisplay_6_4,[[]],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n\n                ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'vg-scrub-bar',(null as any));
    this._appEl_8 = new import2.AppElement(8,0,this,this._el_8);
    var compView_8:any = import32.viewFactory_VgScrubBar0(this.viewUtils,this.injector(8),this._appEl_8);
    this._VgScrubBar_8_4 = new import23.VgScrubBar(new import15.ElementRef(this._el_8),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_8.initComponent(this._VgScrubBar_8_4,[],compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'vg-scrub-bar-current-time',(null as any));
    this._appEl_10 = new import2.AppElement(10,8,this,this._el_10);
    var compView_10:any = import33.viewFactory_VgScrubBarCurrentTime0(this.viewUtils,this.injector(10),this._appEl_10);
    this._VgScrubBarCurrentTime_10_4 = new import24.VgScrubBarCurrentTime(new import15.ElementRef(this._el_10),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_10.initComponent(this._VgScrubBarCurrentTime_10_4,[],compView_10);
    compView_10.create(this._VgScrubBarCurrentTime_10_4,[],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'vg-scrub-bar-buffering-time',(null as any));
    this._appEl_12 = new import2.AppElement(12,8,this,this._el_12);
    var compView_12:any = import34.viewFactory_VgScrubBarBufferingTime0(this.viewUtils,this.injector(12),this._appEl_12);
    this._VgScrubBarBufferingTime_12_4 = new import25.VgScrubBarBufferingTime(new import15.ElementRef(this._el_12),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_12.initComponent(this._VgScrubBarBufferingTime_12_4,[],compView_12);
    compView_12.create(this._VgScrubBarBufferingTime_12_4,[],(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n                ',(null as any));
      compView_8.create(this._VgScrubBar_8_4,[[].concat([
        this._text_9,
        this._el_10,
        this._text_11,
        this._el_12,
        this._text_13
      ]
    )],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n\n                ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'vg-time-display',(null as any));
    this.renderer.setElementAttribute(this._el_15,'format','mm:ss');
    this.renderer.setElementAttribute(this._el_15,'property','left');
    this._appEl_15 = new import2.AppElement(15,0,this,this._el_15);
    var compView_15:any = import31.viewFactory_VgTimeDisplay0(this.viewUtils,this.injector(15),this._appEl_15);
    this._VgTimeDisplay_15_4 = new import22.VgTimeDisplay(new import15.ElementRef(this._el_15),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_15.initComponent(this._VgTimeDisplay_15_4,[],compView_15);
    compView_15.create(this._VgTimeDisplay_15_4,[[]],(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'vg-time-display',(null as any));
    this.renderer.setElementAttribute(this._el_17,'format','mm:ss');
    this.renderer.setElementAttribute(this._el_17,'property','total');
    this._appEl_17 = new import2.AppElement(17,0,this,this._el_17);
    var compView_17:any = import31.viewFactory_VgTimeDisplay0(this.viewUtils,this.injector(17),this._appEl_17);
    this._VgTimeDisplay_17_4 = new import22.VgTimeDisplay(new import15.ElementRef(this._el_17),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_17.initComponent(this._VgTimeDisplay_17_4,[],compView_17);
    compView_17.create(this._VgTimeDisplay_17_4,[[]],(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n\n                ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'vg-mute',(null as any));
    this._appEl_19 = new import2.AppElement(19,0,this,this._el_19);
    var compView_19:any = import35.viewFactory_VgMute0(this.viewUtils,this.injector(19),this._appEl_19);
    this._VgMute_19_4 = new import26.VgMute(new import15.ElementRef(this._el_19),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_19.initComponent(this._VgMute_19_4,[],compView_19);
    compView_19.create(this._VgMute_19_4,[],(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n\n                ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'vg-fullscreen',(null as any));
    this._appEl_21 = new import2.AppElement(21,0,this,this._el_21);
    var compView_21:any = import36.viewFactory_VgFullscreen0(this.viewUtils,this.injector(21),this._appEl_21);
    this._VgFullscreen_21_4 = new import27.VgFullscreen(new import15.ElementRef(this._el_21),this.parent.parentInjector.get(import16.VgAPI));
    this._appEl_21.initComponent(this._VgFullscreen_21_4,[],compView_21);
    compView_21.create(this._VgFullscreen_21_4,[],(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n            ',(null as any));
      compView_0.create(this._VgControls_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_3,
        this._el_4,
        this._text_5,
        this._el_6,
        this._text_7,
        this._el_8,
        this._text_14,
        this._el_15,
        this._text_16,
        this._el_17,
        this._text_18,
        this._el_19,
        this._text_20,
        this._el_21,
        this._text_22
      ]
    )],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_8,'mousedown',this.eventHandler(this._handle_mousedown_8_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.VgPlayPause) && (2 === requestNodeIndex))) { return this._VgPlayPause_2_4; }
    if (((token === import21.VgPlaybackButton) && (4 === requestNodeIndex))) { return this._VgPlaybackButton_4_4; }
    if (((token === import22.VgTimeDisplay) && (6 === requestNodeIndex))) { return this._VgTimeDisplay_6_4; }
    if (((token === import24.VgScrubBarCurrentTime) && (10 === requestNodeIndex))) { return this._VgScrubBarCurrentTime_10_4; }
    if (((token === import25.VgScrubBarBufferingTime) && (12 === requestNodeIndex))) { return this._VgScrubBarBufferingTime_12_4; }
    if (((token === import23.VgScrubBar) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._VgScrubBar_8_4; }
    if (((token === import22.VgTimeDisplay) && (15 === requestNodeIndex))) { return this._VgTimeDisplay_15_4; }
    if (((token === import22.VgTimeDisplay) && (17 === requestNodeIndex))) { return this._VgTimeDisplay_17_4; }
    if (((token === import26.VgMute) && (19 === requestNodeIndex))) { return this._VgMute_19_4; }
    if (((token === import27.VgFullscreen) && (21 === requestNodeIndex))) { return this._VgFullscreen_21_4; }
    if (((token === import19.VgControls) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._VgControls_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._VgControls_0_4.ngOnInit(); }
    const currVal_4:any = 'current';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._VgTimeDisplay_6_4.property = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'mm:ss';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._VgTimeDisplay_6_4.format = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = 'left';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._VgTimeDisplay_15_4.property = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = 'mm:ss';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._VgTimeDisplay_15_4.format = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = 'total';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._VgTimeDisplay_17_4.property = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = 'mm:ss';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._VgTimeDisplay_17_4.format = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._VgControls_0_4.isAdsPlaying;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementStyle(this._el_0,'pointer-events',((this.viewUtils.sanitizer.sanitize(import18.SecurityContext.STYLE,currVal_0) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import18.SecurityContext.STYLE,currVal_0).toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._VgControls_0_4.hideControls;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'hide',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._VgControls_0_4.ngAfterViewInit(); } }
  }
  private _handle_click_2_0($event:any):boolean {
    this._appEl_2.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._VgPlayPause_2_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_4_0($event:any):boolean {
    this._appEl_4.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._VgPlaybackButton_4_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_8_0($event:any):boolean {
    this._appEl_8.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._VgScrubBar_8_4.onMouseDownScrubBar($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this._appEl_19.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._VgMute_19_4.onClick()) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this._appEl_21.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._VgFullscreen_21_4.onClick()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_VrtVideoPlayer1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_VrtVideoPlayer1(viewUtils,parentInjector,declarationEl);
}
class _View_VrtVideoPlayer2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_VrtVideoPlayer2,renderType_VrtVideoPlayer,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'source',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.video.src;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import18.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.video.type;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_0,'type',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_VrtVideoPlayer2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_VrtVideoPlayer2(viewUtils,parentInjector,declarationEl);
}